### List Queues
GET http://localhost:8081/queues
Content-Type: application/json

###

### Create Queue
POST http://localhost:8081/queues
Content-Type: application/json

{
    "queue_name": "testQueue"
}

###

### Publish Message
POST http://localhost:8081/publish
Content-Type: application/json

{
    "exchange_name": "testExchange",
    "routing_key": "testkey",
    "message": "Hello, World! 3"
}

### Create Exchange
POST http://localhost:8081/exchanges
Content-Type: application/json

{
    "exchange_name": "testExchange",
    "exchange_type": "direct"
}

### Bind Queue to Exchange
POST http://localhost:8081/bindings

{
    "exchange_name": "testExchange",
    "queue_name": "testQueue",
    "routing_key": "testkey"
}

### Consume Messages
POST http://localhost:8081/consume
Content-Type: application/json

{
    "queue_name": "testQueue"
}

### Acknowledge Message
POST http://localhost:8081/ack
Content-Type: application/json

{
    "msg_id": "5e531760-da0a-4e5a-a231-1ea0f046420e"
}

### Delete Queue
POST http://localhost:8081/delete
Content-Type: application/json

{
    "queue_name": "testQueue"
}