@host = http://localhost:8081
@queue_name = testQueue
@exchange_name = testExchange
@routing_key = testkey
@message_id = cea37d9d-bd83-47aa-b29a-fc4554457b2c

### List Queues
GET {{host}}/queues
Content-Type: application/json


### Create Queue
POST {{host}}/queues
Content-Type: application/json

{
    "queue_name": "{{queue_name}}"
}

### Delete Queue
DELETE {{host}}/queues/{{queue_name}}
Content-Type: application/json

###

### Publish Message
POST {{host}}/messages
Content-Type: application/json

{
    "exchange_name": "{{exchange_name}}",
    "routing_key": "{{routing_key}}",
    "message": "Hello, World!"
}


### Create Exchange
POST {{host}}/exchanges
Content-Type: application/json

{
    "exchange_name": "{{exchange_name}}",
    "exchange_type": "direct"
}

###

### List Exchanges
GET {{host}}/exchanges
Content-Type: application/json

###

### Delete Exchange
DELETE {{host}}/exchanges/{{exchange_name}}
Content-Type: application/json

###

### Bind Queue to Exchange
POST {{host}}/bindings
Content-Type: application/json

{
    "exchange_name": "{{exchange_name}}",
    "queue_name": "{{queue_name}}",
    "routing_key": "{{routing_key}}"
}

###

### Delete Binding
DELETE  {{host}}/bindings
Content-Type: application/json

{
    "exchange_name": "{{exchange_name}}",
    "queue_name": "{{queue_name}}",
    "routing_key": "{{routing_key}}"
}

###

### List Bindings
GET {{host}}/bindings/{{exchange_name}}
Content-Type: application/json

###

### Consume Messages
POST {{host}}/queues/{{queue_name}}/consume
Content-Type: application/json

###

### Count Messages
GET {{host}}/queues/{{queue_name}}/count
Content-Type: application/json

###

### Acknowledge Message
POST {{host}}/messages/{{message_id}}/ack
Content-Type: application/json

###