definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  models.CreateExchangeRequest:
    properties:
      exchange_name:
        type: string
      exchange_type:
        type: string
    type: object
  models.CreateQueueRequest:
    properties:
      queue_name:
        type: string
    type: object
  models.FiberMap:
    additionalProperties: true
    type: object
info:
  contact: {}
paths:
  /api/exchanges:
    get:
      consumes:
      - application/json
      description: Get a list of all exchanges
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FiberMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FiberMap'
      summary: List all exchanges
      tags:
      - exchanges
    post:
      consumes:
      - application/json
      description: Create a new exchange with the specified name and type
      parameters:
      - description: Exchange to create
        in: body
        name: exchange
        required: true
        schema:
          $ref: '#/definitions/models.CreateExchangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FiberMap'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.FiberMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FiberMap'
      summary: Create a new exchange
      tags:
      - exchanges
  /api/exchanges/{exchange}:
    delete:
      consumes:
      - application/json
      description: Delete an exchange with the specified name
      parameters:
      - description: Exchange name
        in: path
        name: exchange
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FiberMap'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.FiberMap'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FiberMap'
      summary: Delete an exchange
      tags:
      - exchanges
  /api/queues:
    get:
      consumes:
      - application/json
      description: Get a list of all queues
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: List all queues
      tags:
      - queues
    post:
      consumes:
      - application/json
      description: Create a new queue with the specified name
      parameters:
      - description: Queue to create
        in: body
        name: queue
        required: true
        schema:
          $ref: '#/definitions/models.CreateQueueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create a new queue
      tags:
      - queues
  /api/queues/{queue}:
    delete:
      consumes:
      - application/json
      description: Delete a queue with the specified name
      parameters:
      - description: Queue name
        in: path
        name: queue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete a queue
      tags:
      - queues
  /api/queues/{queue}/consume:
    post:
      consumes:
      - application/json
      description: Consume a message from the specified queue
      parameters:
      - description: Queue name
        in: path
        name: queue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Consume a message from a queue
      tags:
      - queues
  /api/queues/{queue}/count:
    get:
      consumes:
      - application/json
      description: Count the number of messages in the specified queue
      parameters:
      - description: Queue name
        in: path
        name: queue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Count messages in a queue
      tags:
      - queues
swagger: "2.0"
